[package]
name = "crate_serde_json_convert_anything_to_value_enum"
version = "0.1.0"
authors = ["slyo <sean.lyo@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "=1.0.114", features = ["derive"]}
serde_json = "=1.0.55"
