[package]
name = "crate_docker-api_docker_interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docker-api = "^0.4"
tokio = {version = "^1", features = ["full"]}
