[package]
name = "action_expression_evaluation_during_compilation"
version = "0.1.0"
authors = ["Sean Lyo <137232774@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
