[package]
name = "crate_rayon_iter_parallel"
version = "0.1.0"
authors = ["_fy <liuxiaochuan@novogene.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
