[package]
name = "crate_redb_embeded_key_value_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redb = "0.1.2"
