[package]
name = "crate_indicatif_progress_bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "^0.16"
rand = "^0.8"
console = { version = ">=0.9.1, <1.0.0", default-features = false }
