[package]
name = "crate_zip_zip_archives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "^0.6"
walkdir = "^2.3"

[features]
deflate = []
zstd = []
bzip2 = []
