[package]
name = "crate_minijinja_templating"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minijinja = "^0.3"
serde = {version = "^1", features = ["derive"]}
