[package]
name = "crate_doku_doc_from_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
doku = "^0.10"
serde = {version = "^1", features = ["derive"]}
