[package]
name = "crate_expectrl_terminal_iteraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expectrl = "^0.2"
