[package]
name = "crate_mupdf_read_write_pdf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mupdf = "^0.1"
