[package]
name = "crate_tokio-cron-scheduler_cron_job"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
tokio = { version = "^1", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "^0.5"
