[package]
name = "crate_mp4ameta_read_write_MPEG-4_audio_metadata"
version = "0.1.0"
authors = ["Sean Lyo <137232774@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4ameta = "*"
