[package]
name = "crate_libwfa_wavefront_algorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libwfa = "0.1.2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
