[package]
name = "crate_rug_dealing_with_big_numbers"
version = "0.1.0"
authors = ["Sean Lyo <137232774@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.7.0"
