[package]
name = "crate_bollard_docker_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "^0.11"
tokio = {version = "^1", features=["macros"]}
