[package]
name = "crate_prettyplease_syntax_printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettyplease = "^0.1"
syn = { version = "1", default-features = false, features = ["full", "parsing"] }
