[package]
name = "crate_infinitree_embeded_database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infinitree = "^0.2.1"
serde = {version = "^1", features = ["derive"]}
