[package]
name = "crate_headless-chrome_control_headless_chrome"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "^0.9"
failure = "^0.1"
