[package]
name = "crate_memuse_measure_dynamic_memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memuse = "^0.2"
