[package]
name = "crate_shiplift_docker_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shiplift = "^0.7"
futures = "^0.3"
tokio = {version = "^1", features = ["macros"]}
